config/routes.rb
Rails.application.routes.draw do

  get 'activity', to: 'pages#activity'
  get 'activity/questions', to: 'pages#questions'
  get 'activity/answers', to: 'pages#answers'
  get 'policy', to: 'pages#policy'
  get 'lajk', to: 'answers#like'

  get 'search', to: 'questions#search'

  


  devise_for :people, controllers: { omniauth_callbacks: 'people/omniauth_callbacks' }
  resources :questions do
    resources :answers, only: [:create, :destroy] do
      #resources :likes, only: [:create, :destroy]
      member do
        patch "upvote", to: "answers#upvote"
        patch "downvote", to: "answers#downvote"
      end
    end
  end



  #get 'home/index'



  root "questions#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :person
    has_many :answers
    accepts_nested_attributes_for :answers, allow_destroy: true
    has_rich_text :questionn
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_person!, only: %i[ edit update destroy create ]
  before_action :set_person
 
  def search
    @questions = Question.where("UPPER(title) LIKE ?", "%" + params[:q].upcase + "%")

  end

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
      @answers = @question.answers.where(parent_id: nil)
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :body, :person_id, :questionn)
    end

    def set_person
      @person = current_person
    end

    
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="field form-group">
    <% form.label :body %>
    <% form.text_area :body, class:'form-control', rows:'5' %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.rich_text_area :questionn %>
  </div>

  <div class="field form-group">
    <% if person_signed_in? %>
      <%= form.number_field :person_id, id: :question_person_id, value: current_person.id, type: :hidden %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class:'btn btn-primary' %>
  </div>
</form>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>
<br>
<hr>
<br>

<%= render 'form', question: @question %>

<% link_to 'Show', @question %>
<% link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<%= render "home/left" %>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>Questions</h1>
    </div>
    <div class="col-sm">
      <%= link_to 'Ask Question', new_question_path, class:"btn btn-info question", style:"color:white" %>
    </div>
  </div>
</div>
<br>
<hr>
<br>

<table>
    <% @questions.each do |question| %>
      <tr>
        <td class="smallTD"><%= question.answers.count %> answers</td>
        <td class="wide"><p class="top wrap"> <%= link_to question.title, question, class:"link" %> </p></td>

        
        <!--<td><%# image_tag question.person.avatar, width: "20px", height: "20px" %></td>-->
        <!--<td><%# question.title %></td>
        <td><% question.body %></td>
        <td><% link_to 'Show', question %></td>
        <td><% link_to 'Edit', edit_question_path(question) %></td>
        <td><% link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
      <tr class="underline">
        <td colspan="2">
        <span class="right">
        <% if question.person.avatar.attached? %>
        <%= image_tag question.person.avatar, width: "20px", height: "20px" %>
        <% else %>
        <%= image_tag ("default.jpg"), width: "20px", height: "20px" %>
        <% end %>
        <!--<img class="pic" width="20" height="20"> -->
        <%= question.person.username %>
        </span>
        </td>
      </tr>
    <% end %>
</table>

<br>

app/views/questions/new.html.erb
<%= render "home/left" %>



<h1>New Question</h1>
<br><br>

<%= render 'form', question: @question %>

<% link_to 'Back', questions_path %>

app/views/questions/search.html.erb
<%= render "home/left" %>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>Questions</h1>
    </div>
    <div class="col-sm">
      <%= link_to 'Ask Question', new_question_path, class:"btn btn-info question", style:"color:white" %>
    </div>
  </div>
</div>
<br>
<hr>
<br>

<table>
    <% @questions.each do |question| %>
      <tr>
        <td class="smallTD"><%= question.answers.count %> answers</td>
        <td class="wide"><p class="top wrap"> <%= link_to question.title, question, class:"link" %> </p></td>

        
        <!--<td><%# image_tag question.person.avatar, width: "20px", height: "20px" %></td>-->
        <!--<td><%# question.title %></td>
        <td><% question.body %></td>
        <td><% link_to 'Show', question %></td>
        <td><% link_to 'Edit', edit_question_path(question) %></td>
        <td><% link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
      <tr class="underline">
        <td colspan="2">
        <span class="right">
        <% if question.person.avatar.attached? %>
        <%= image_tag question.person.avatar, width: "20px", height: "20px" %>
        <% else %>
        <%= image_tag ("default.jpg"), width: "20px", height: "20px" %>
        <% end %>
        <!--<img class="pic" width="20" height="20"> -->
        <%= question.person.username %>
        </span>
        </td>
      </tr>
    <% end %>
</table>

<br>

app/views/questions/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<%= render "home/left" %>

<div>
<table class="wide">
<tr><td class="wide">
  <h2 class="wrap"><%= @question.title %></h2>
  <hr>
</td></tr>
<tr><td>
  <p>
    <%= @question.questionn %>
  </p>
</td></tr>
<tr><td>

<div style="float:right">
<table>
  <tr>
    <td> Asked: <%= @question.created_at.strftime("%a %d, %H:%M") %> </td>
  </tr>
  <tr>
    <td>
      <% if @question.person.avatar.attached? %>
          <%= image_tag @question.person.avatar, width: "35px", height: "35px" %>
      <% else %>
          <%= image_tag ("default.jpg"), width: "35px", height: "35px" %>
      <% end %>
        <%= @question.person.username %> 
    </td>
  </tr>
</table>
</div>

<tr><td>

<div style="float:left"><p>
  Answers: 
  <%= @answers.count %>
</p></div>
</td></tr>

</td></tr>


</table>
<div>

<p>
  <%= render @question.answers.where(parent_id: nil).order(cached_weighted_score: :desc) %>
  <%= render partial: 'answers/form', locals: { question: @question, parent: @answer } %>
</p>
  



<% link_to 'Edit', edit_question_path(@question) %>
<% link_to 'Back', questions_path %>