config/routes.rb
Rails.application.routes.draw do

  get 'activity', to: 'pages#activity'
  get 'activity/questions', to: 'pages#questions'
  get 'activity/answers', to: 'pages#answers'
  get 'policy', to: 'pages#policy'
  get 'lajk', to: 'answers#like'

  get 'search', to: 'questions#search'

  


  devise_for :people, controllers: { omniauth_callbacks: 'people/omniauth_callbacks' }
  resources :questions do
    resources :answers, only: [:create, :destroy] do
      #resources :likes, only: [:create, :destroy]
      member do
        patch "upvote", to: "answers#upvote"
        patch "downvote", to: "answers#downvote"
      end
    end
  end



  #get 'home/index'



  root "questions#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <!--<a class="navbar-brand">Navbar</a>-->
  <%= link_to "StackCloud", questions_path, class:"navbar-brand" %>
  <form class="form-inline" action="/search">
    <input size="50" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <span class="navbar-text">
    <% if person_signed_in? %>
    <br>
    <% if @person.avatar.attached? %>
        <%= image_tag @person.avatar, width: "40px", height: "40px" %>
        <% else %>
        <%= image_tag ("default.jpg"), width: "40px", height: "40px" %>
        <% end %>

    <%= link_to @person.username, edit_person_registration_path %>
    <% link_to 'Sign Out', destroy_person_session_path, method: :delete %>
    <% else %>
    
    <%= link_to 'Sign in  ', new_person_session_path %>
    <%= link_to 'Sign up', new_person_registration_path %>
    <% end %>
  </span>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/home/_left.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 left line">
    <h4>HOME</h4>
    <br>
    <p>PUBLIC</p>
    <ul>
      <li><%= link_to "Questions", questions_path %></li>
      <li><%= link_to 'My Profile', edit_person_registration_path %></li>
      <li><%= link_to 'My Activity', activity_path %></li>
    </ul>
    </div>
    <div class="col-8">
    
    
  

app/views/home/index.html.erb
BODY

    