config/routes.rb
Rails.application.routes.draw do

  get 'activity', to: 'pages#activity'
  get 'activity/questions', to: 'pages#questions'
  get 'activity/answers', to: 'pages#answers'
  get 'policy', to: 'pages#policy'
  get 'lajk', to: 'answers#like'

  get 'search', to: 'questions#search'

  


  devise_for :people, controllers: { omniauth_callbacks: 'people/omniauth_callbacks' }
  resources :questions do
    resources :answers, only: [:create, :destroy] do
      #resources :likes, only: [:create, :destroy]
      member do
        patch "upvote", to: "answers#upvote"
        patch "downvote", to: "answers#downvote"
      end
    end
  end



  #get 'home/index'



  root "questions#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  acts_as_votable

  belongs_to :question
  belongs_to :person
  belongs_to :parent, class_name: "Answer", optional: true
  has_many :answers, foreign_key: :parent_id

  has_many :likes, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :set_answer, only: [:edit, :update, :show, :destroy, :like, :unlike]
    before_action :authenticate_person! 



    def upvote
        @answer = Answer.find(params[:id])
        if current_person.voted_up_on? @answer
          @answer.unvote_by current_person
        else
          @answer.upvote_by current_person
        end
        redirect_to question_path(params[:question_id])
        #render "vote.js.erb"
        
    end
    
    def downvote
        @answer = Answer.find(params[:id])
        if current_person.voted_down_on? @answer
          @answer.unvote_by current_person
        else
          @answer.downvote_by current_person
        end
        redirect_to question_path(params[:question_id])
        #render "vote.js.erb"
    end
    


    def destroy
        Answer.find(params[:id]).destroy
        redirect_to activity_path
    end

    def create
        #create a new answer
        @answer = current_person.answers.new(answer_params)
        if !@answer.save
            flash[:notice] = @answer.errors.full_messages.to_sentence
        end

        redirect_to question_path(params[:question_id])
    end

    def like
        @answer.liked_by current_person
        respond_to do |format|
            format.html {redirect_back fallback_location: root_path}
        end
    end

    def unlike
        @answer.unliked_by current_person
        respond_to do |format|
            format.html {redirect_back fallback_location: root_path}
        end
    end

    private

    def answer_params
        params
        .require(:answer)
        .permit(:content, :parent_id)
        .merge(question_id: params[:question_id])
    end

    def set_answer
        @answer = Answer.find(params[:id])
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<% pre_like = answer.likes.find { |like| like.person_id == current_person.id} %>
<% link_to 'Delete', question_answer_path(@question, answer), method: :delete %>



<% if answer.parent_id == nil %>
<hr>
<% end %>
<table style="margin-top:20px"><tr>
<td>
<table>
<tr><td class="textarea">  <%= render 'answers/upvote_link', answer: answer %>  </td></tr>
<tr><td class="textarea centerT">  <%= render 'answers/votes_score', answer: answer %>  </td></tr>
<tr><td class="textarea">  <%= render 'answers/downvote_link', answer: answer %>  </td></tr>
</table></td>

<% if answer.parent_id != nil %>
<td class="wide underline">
<% else %>
<td class="wide">
<% end %>
<div class="wide">
    
    
    <% if answer.parent_id != nil %>
    <p class="zero comment"><%= answer.content %> <span class="nekaj">
    - <span style="color:blue"><%= answer.person.username %>
    </span>
    <span style="color:grey">
    <%=answer.created_at.strftime("%a %d, %H:%M")%>
    </span>

    <% else %>

    <p class="zero"><%= answer.content %> <span class="nekaj">
    <% end %>

    </span></p>
</div>
</td></tr>



<tr class="textarea"><td colspan="2">
<span class="right">
<table><tr><td>

Answered:
<%= answer.created_at.strftime("%a %d, %H:%M") %>

</td></tr>
<tr><td>

<% if answer.person.avatar.attached? %>
<%= image_tag answer.person.avatar, width: "35px", height: "35px" %>
<% else %>
<%= image_tag ("default.jpg"), width: "35px", height: "35px" %>
<% end %>
<%= answer.person.username %>
</td></tr>
</table>
</span>
</td></tr>





</table>

<a href="" class="comment-form-display textarea">Add a comment</a>

<div class="comment-form">
    <%= render partial: 'answers/form_comment', locals: { question: @question, parent: answer }%>
</div>

<% if answer.parent_id == nil %>
<hr>
<% end %>

<div class="sub-comment wrap comment">
<%= render answer.answers %>
</div>






<script>

    document.querySelectorAll('.comment-form-display').forEach((el) => {
    el.addEventListener('click', (ev) => {
        ev.preventDefault();
        el.nextElementSibling.style = 'display: block;'
    })
})

</script>




app/views/answers/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{answer.id}" do %>
<%= link_to downvote_question_answer_path(@question, answer) , method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if person_signed_in? %>
    <% if current_person.voted_down_on? answer %>
      <i class="arrowdo"></i>
    <% else %>
      <i class="arrow2"></i>
    <% end %>
    <% else %>
      <i class="arrow2"></i>
    <% end %>
  <% end %>
<% end %>


app/views/answers/_form.html.erb

<form action="<%= question_answers_path(question)%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if !parent.nil? %>
        <input type="hidden" name="answer[parent_id]" value="<%= parent.id %>">
    <% end %>

    <div>
        <textarea class="textarea" name="answer[content]" rows="6" cols="20"></textarea>
    </div>

    <input class="textarea" type="submit" value="submit">
</form>



app/views/answers/_form_comment.html.erb
<hr>
<p>Your Comment</p>
<form action="<%= question_answers_path(question)%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if !parent.nil? %>
        <input type="hidden" name="answer[parent_id]" value="<%= parent.id %>">
    <% end %>

    <div>
        <textarea style="max-width:100vh" class="textarea" name="answer[content]" rows="3" cols="200"></textarea>
    </div>
    <input class="textarea" type="submit" value="Submit">
</form>

app/views/answers/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{answer.id}" do %>
<%= link_to upvote_question_answer_path(@question, answer) , method: :patch, remote: true do %>
    <% if person_signed_in? %>

      <% if current_person.voted_up_on? answer %>
        <i class="arrowo"></i>
      <% else %>
        <i class="arrow1"></i>
      <% end %>

    <% else %>
      <i class="arrow1"></i>
    <% end %>

  <% end %>
<% end %>


app/views/answers/_votes_score.html.erb
<%= content_tag "div", id: "votes-score-#{answer.id}" do %>
  <% answer.cached_votes_score %>
  <%= answer.get_likes.size - answer.get_dislikes.size  %>
<% end %>

app/views/answers/vote.js.erb
document.getElementById("upvote-<%= @answer.id %>").innerHTML = "<%= j render "answers/upvote_link", answer: @answer %>";
document.getElementById("downvote-<%= @answer.id %>").innerHTML = "<%= j render "answers/downvote_link", answer: @answer %>";

document.getElementById("votes-score-<%= @answer.id %>").innerHTML = "<%= j render "answers/votes_score", answer: @answer %>";