config/routes.rb
Rails.application.routes.draw do

  get 'activity', to: 'pages#activity'
  get 'activity/questions', to: 'pages#questions'
  get 'activity/answers', to: 'pages#answers'
  get 'policy', to: 'pages#policy'
  get 'lajk', to: 'answers#like'

  get 'search', to: 'questions#search'

  


  devise_for :people, controllers: { omniauth_callbacks: 'people/omniauth_callbacks' }
  resources :questions do
    resources :answers, only: [:create, :destroy] do
      #resources :likes, only: [:create, :destroy]
      member do
        patch "upvote", to: "answers#upvote"
        patch "downvote", to: "answers#downvote"
      end
    end
  end



  #get 'home/index'



  root "questions#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_questions.html.erb
<% @questions.each do |question| %>
    <div class="vprasanja">
      <tr>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
      </tr>
    </div>
<% end %>

app/views/pages/_top.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <!--<a class="nav-link" href="#">Profile</a>-->
    <%= link_to 'Profile', edit_person_registration_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Activity', activity_path, class:"nav-link active" %>
    <!--<a class="nav-link active" href="#">My Activity</a>-->
  </li>
</ul>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
    Select
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to 'questions', activity_questions_path, class:"dropdown-item" %>
    <%= link_to 'answers', activity_answers_path, class:"dropdown-item" %>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>

app/views/pages/activity.html.erb
<%= render "home/left" %>


<ul class="nav nav-tabs">
  <li class="nav-item">
    <!--<a class="nav-link" href="#">Profile</a>-->
    <%= link_to 'Profile', edit_person_registration_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Activity', activity_path, class:"nav-link active" %>
    <!--<a class="nav-link active" href="#">My Activity</a>-->
  </li>
</ul>
<br><br><br>
<h1>My Questions</h1>
<br>
<div id="vprasanja">
<% @questions.each do |question| %>
    <div class="vprasanja wide underline black">
      <tr>
        <td>
        <% question.title %>
        <span class="wrap"><%= link_to question.title, question %></span>
        </td>
        <td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class:"blue" %></td>
        <td><%= link_to 'Edit', edit_question_path(question), class:"blue" %></td>
      </tr>
    </div>
<% end %>
</div>

<hr>
<h1>My Comments</h1>
<br>
<div id="odgovori">
<% @comments.each do |comment| %>
<%# @questions.each do |question| %>
    <div class="vprasanja wide underline">
      <tr>
        <td><span class="wrap"><%= link_to comment.content, comment.question %> </span></td>
      </tr>
      <tr>
        <td><%= link_to 'Delete', question_answer_path(comment.question_id, comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"blue" %></td>
      </tr>
    </div>
<%# end %>
<% end %>
</div>

<hr>
<h1>My answers</h1>
<br>
<div id="odgovori">
<% @answers.each do |answer| %>
<%# @questions.each do |question| %>
    <div class="vprasanja wide underline">
      <tr>
        <td><span class="wrap"><%= link_to answer.content, answer.question %><% answer.content %></span></td>
      </tr>
      <tr>
        <td><%= link_to 'Delete', question_answer_path(answer.question_id, answer), method: :delete, data: { confirm: 'Are you sure?' }, class:"blue" %></td>
      </tr>
    </div>
<%# end %>
<% end %>
</div>






app/views/pages/answers.html.erb
<body>
    <head>

        <title>Log In</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.sstatic.net/Shared/stacks.css?v=d476cb5a215b">
    <link rel="stylesheet" type="text/css" href="https://cdn.sstatic.net/Sites/stackoverflow/primary.css?v=28026a8c646c">


    <div class="flex--item">

        <div class="ta-center fs-title mx-auto mb24">
                    <a href="https://stackoverflow.com">
                        <svg aria-hidden="true" class="native svg-icon iconLogoGlyphMd" width="32" height="37" viewBox="0 0 32 37"><path d="M26 33v-9h4v13H0V24h4v9h22Z" fill="#BCBBBB"></path><path d="m21.5 0-2.7 2 9.9 13.3 2.7-2L21.5 0ZM26 18.4 13.3 7.8l2.1-2.5 12.7 10.6-2.1 2.5ZM9.1 15.2l15 7 1.4-3-15-7-1.4 3Zm14 10.79.68-2.95-16.1-3.35L7 23l16.1 2.99ZM23 30H7v-3h16v3Z" fill="#F48024"></path></svg> 
                    </a>
        </div>
        



<div id="openid-buttons" class="mx-auto d-flex flex__fl-grow1 fd-column gs8 gsy mb16 wmx3">
        <button class="flex--item s-btn s-btn__icon s-btn__google bar-md ba bc-black-100" data-provider="google" data-oauthserver="https://accounts.google.com/o/oauth2/auth" data-oauthversion="2.0">
            <svg aria-hidden="true" class="native svg-icon iconGoogle" width="18" height="18" viewBox="0 0 18 18"><path d="M16.51 8H8.98v3h4.3c-.18 1-.74 1.48-1.6 2.04v2.01h2.6a7.8 7.8 0 0 0 2.38-5.88c0-.57-.05-.66-.15-1.18Z" fill="#4285F4"></path><path d="M8.98 17c2.16 0 3.97-.72 5.3-1.94l-2.6-2a4.8 4.8 0 0 1-7.18-2.54H1.83v2.07A8 8 0 0 0 8.98 17Z" fill="#34A853"></path><path d="M4.5 10.52a4.8 4.8 0 0 1 0-3.04V5.41H1.83a8 8 0 0 0 0 7.18l2.67-2.07Z" fill="#FBBC05"></path><path d="M8.98 4.18c1.17 0 2.23.4 3.06 1.2l2.3-2.3A8 8 0 0 0 1.83 5.4L4.5 7.49a4.77 4.77 0 0 1 4.48-3.3Z" fill="#EA4335"></path></svg>
Log in with Google        </button>
        <button class="flex--item s-btn s-btn__icon s-btn__github bar-md ba bc-black-100" data-provider="github" data-oauthserver="https://github.com/login/oauth/authorize" data-oauthversion="2.0">
            <svg aria-hidden="true" class="svg-icon iconGitHub" width="18" height="18" viewBox="0 0 18 18"><path d="M9 1a8 8 0 0 0-2.53 15.59c.4.07.55-.17.55-.38l-.01-1.49c-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.42 7.42 0 0 1 4 0c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48l-.01 2.2c0 .21.15.46.55.38A8.01 8.01 0 0 0 9 1Z" fill="#010101"></path></svg>
Log in with GitHub        </button>
        <button class="flex--item s-btn s-btn__icon s-btn__facebook bar-md" data-provider="facebook" data-oauthserver="https://www.facebook.com/v2.0/dialog/oauth" data-oauthversion="2.0">
            <svg aria-hidden="true" class="svg-icon iconFacebook" width="18" height="18" viewBox="0 0 18 18"><path d="M3 1a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H3Zm6.55 16v-6.2H7.46V8.4h2.09V6.61c0-2.07 1.26-3.2 3.1-3.2.88 0 1.64.07 1.87.1v2.16h-1.29c-1 0-1.19.48-1.19 1.18V8.4h2.39l-.31 2.42h-2.08V17h-2.5Z" fill="#4167B2"></path></svg>
Log in with Facebook        </button>
</div>

<div id="formContainer" class="mx-auto mb24 p24 wmx3 bg-white bar-lg auth-shadow mb24">
    <form id="login-form" class="d-flex fd-column gs12 gsy" action="/users/login?ssrc=head&amp;returnurl=https%3a%2f%2fstackoverflow.com%2f" method="POST">
        <input type="hidden" name="fkey" value="cf8f28f722438b9c3ecf927929f12a32a46fe1205481dc503cdf30cab353adb1">
            <input type="hidden" name="ssrc" value="head">
                <div class="d-flex fd-column gs4 gsy js-auth-item ">
                    <label class="flex--item s-label" for="email">Email</label>
                    <div class="d-flex ps-relative">
                        <input class="s-input" id="email" type="email" size="30" maxlength="100" name="email">
                        <svg aria-hidden="true" class="s-input-icon js-alert-icon d-none svg-icon iconAlertCircle" width="18" height="18" viewBox="0 0 18 18"><path d="M9 17c-4.36 0-8-3.64-8-8 0-4.36 3.64-8 8-8 4.36 0 8 3.64 8 8 0 4.36-3.64 8-8 8ZM8 4v6h2V4H8Zm0 8v2h2v-2H8Z"></path></svg>
                    </div>
                            <p class="flex--item s-input-message js-error-message d-none">
            
        </p>

                </div>
                <div class="d-flex fd-column-reverse gs4 gsy js-auth-item ">
                            <p class="flex--item s-input-message js-error-message d-none">
            
        </p>

                    <div class="d-flex ps-relative js-password">
                        <input class="flex--item s-input" type="password" autocomplete="off" name="password" id="password">
                        <svg aria-hidden="true" class="s-input-icon js-alert-icon d-none svg-icon iconAlertCircle" width="18" height="18" viewBox="0 0 18 18"><path d="M9 17c-4.36 0-8-3.64-8-8 0-4.36 3.64-8 8-8 4.36 0 8 3.64 8 8 0 4.36-3.64 8-8 8ZM8 4v6h2V4H8Zm0 8v2h2v-2H8Z"></path></svg>
                    </div>
                    <div class="d-flex ai-center ps-relative jc-space-between">
                        <label class="flex--item s-label" for="password">Password</label>

                            <a class="flex--item s-link fs-caption" href="/users/account-recovery">Forgot password?</a>
                    </div>
                </div>
            <div class="d-flex gs4 gsy fd-column js-auth-item ">
                <button class="flex--item s-btn s-btn__primary" id="submit-button" name="submit-button">Log in</button>
                        <p class="flex--item s-input-message js-error-message d-none">
            
        </p>

            </div>

        <input type="hidden" id="oauth_version" name="oauth_version">
        <input type="hidden" id="oauth_server" name="oauth_server">


    </form>
</div>

<script>
    StackExchange.ready(function () {

        StackExchange.using("gps", function() { StackExchange.gps.sendPending(); });

    });

</script>

            <div class="mx-auto ta-center fs-body1 p16 pb0 mb24 w100 wmx3">
                Don’t have an account? <a href="/users/signup?ssrc=head&amp;returnurl=https%3a%2f%2fstackoverflow.com%2f">Sign up</a>
            </div>
</div>
    </body>

app/views/pages/policy.html.erb
HEYYYYY

app/views/pages/questions.html.erb
<%= render 'pages/top'%>

<% @questions.each do |question| %>
    <div class="vprasanja">
      <tr>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
      </tr>
    </div>
<% end %>